### ISSUE TITLE
Can't upgrade to v2

### ISSUE THREAD

**Issue by jlelse** [vcraescu/go-paginator#6]
When trying to run:

```
go get -u github.com/vcraescu/go-paginator@v2.0.0
```

There's this error:

```
go get github.com/vcraescu/go-paginator@v2.0.0: github.com/vcraescu/go-paginator@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

See https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by vcraescu** [comment]
Thank yo for reporting this issue! This is fixed.

**Comment by jlelse** [comment]
You probably have to issue a new release, because it's still cached by the Go module proxy
